
package crud_pbo;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class CRUD_Pbo1 extends javax.swing.JFrame {

    /**
     * Creates new form CRUD_Pbo1
     */
    public CRUD_Pbo1() {
        initComponents();
        Connect();
        loadPusakaId();
        
    }
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        
    public void Connect(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
                try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/pusaka","root","");
            } catch (SQLException ex) {
                Logger.getLogger(CRUD_Pbo1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CRUD_Pbo1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void loadPusakaId(){
        try {
            pst = con.prepareStatement("select id_item from data");
            rs = pst.executeQuery ();
            
            txtid.removeAllItems();
            while (rs.next()){
            txtid.addItem(rs.getString(1).toString());
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(CRUD_Pbo1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtJudulBuku = new javax.swing.JTextField();
        txtnamaPenulis = new javax.swing.JTextField();
        txtJenisBuku = new javax.swing.JTextField();
        txtnamaPenerbit = new javax.swing.JTextField();
        txttahunTerbit = new javax.swing.JTextField();
        txtid = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton_ADD = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_view = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        txtidbuku = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 50, 65), 8));

        jLabel2.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 50, 65));
        jLabel2.setText("ID Buku");

        jLabel3.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 50, 65));
        jLabel3.setText("Judul Buku");

        jLabel4.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(41, 50, 65));
        jLabel4.setText("Jenis Buku");

        jLabel5.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(41, 50, 65));
        jLabel5.setText("Nama Penulis");

        jLabel6.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(41, 50, 65));
        jLabel6.setText("Nama Penerbit");

        jLabel7.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(41, 50, 65));
        jLabel7.setText("Tahun Terbit");

        txtJudulBuku.setBackground(new java.awt.Color(237, 237, 237));

        txtnamaPenulis.setBackground(new java.awt.Color(237, 237, 237));

        txtJenisBuku.setBackground(new java.awt.Color(237, 237, 237));

        txtnamaPenerbit.setBackground(new java.awt.Color(237, 237, 237));

        txttahunTerbit.setBackground(new java.awt.Color(237, 237, 237));

        txtid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 199, 200));
        jLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(148, 195, 211));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PUSAKA");

        jButton_ADD.setText("ADD");
        jButton_ADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ADDActionPerformed(evt);
            }
        });

        jButton_clear.setText("CLEAR");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_view.setText("VIEW");
        jButton_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_viewActionPerformed(evt);
            }
        });

        jButton_delete.setText("DELETE");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jButton_edit.setText("EDIT");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        txtidbuku.setBackground(new java.awt.Color(237, 237, 237));

        jLabel8.setFont(new java.awt.Font("Montserrat SemiBold", 0, 23)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 20, 26));
        jLabel8.setText("DIGITALIBRARY.");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crud_pbo/ANYARRR.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton_ADD)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton_view)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                                .addComponent(jButton_edit)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton_delete))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtnamaPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtnamaPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txttahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtJenisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(txtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(21, 21, 21)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jButton_clear, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(154, 154, 154))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_clear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJenisBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamaPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamaPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttahunTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ADD)
                    .addComponent(jButton_view)
                    .addComponent(jButton_delete)
                    .addComponent(jButton_edit))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed

        String id = txtid.getSelectedItem().toString();

        try {

            String idbuku    = txtidbuku.getText();
            String judul    = txtJudulBuku.getText();
            String jenis    = txtJenisBuku.getText();
            String penulis  = txtnamaPenulis.getText();
            String penerbit  = txtnamaPenerbit.getText();
            String tahun  = txttahunTerbit.getText();

            pst = con.prepareStatement("update data set id_buku=?, judul_buku=? ,jenis_buku=? ,nama_penulis=? ,nama_penerbit=? ,tahun_terbit=? where id_item=? ");

            pst.setString(1,idbuku);
            pst.setString(2,judul);
            pst.setString(3,jenis);
            pst.setString(4,penulis);
            pst.setString(5,penerbit);
            pst.setString(6,tahun);
            pst.setString(7,id);

            int k = pst.executeUpdate();

            if (k==1){
                JOptionPane.showMessageDialog(this,"Data Berhasil Di Edit");
                txtidbuku.setText("");
                txtJudulBuku.setText("");
                txtJenisBuku.setText("");
                txtnamaPenulis.setText("");
                txtnamaPenerbit.setText("");
                txttahunTerbit.setText("");
                loadPusakaId();

            }
            else{
                JOptionPane.showMessageDialog(this,"Data Tidak Berhasil Di Edit");
            }

        } catch (SQLException ex) {
            Logger.getLogger(CRUD_Pbo1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        try {
            String id = txtid.getSelectedItem().toString();
            pst = con.prepareStatement("delete from data where id_item=?");
            pst.setString(1,id);

            int k = pst.executeUpdate();

            if (k==1 ){
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                txtidbuku.setText(rs.getString(2));
                txtJudulBuku.setText(rs.getString(3));
                txtJenisBuku.setText(rs.getString(4));
                txtnamaPenulis.setText(rs.getString(5));
                txtnamaPenerbit.setText(rs.getString(6));
                txttahunTerbit.setText(rs.getString(7));
                loadPusakaId();

            }else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus");
            }
        } catch (SQLException ex) {
            Logger.getLogger(CRUD_Pbo1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_viewActionPerformed

        try {
            String id = txtid.getSelectedItem().toString();
            pst = con.prepareStatement("select*from data where id_item=?");
            pst.setString(1,id);
            rs = pst.executeQuery();

            if (rs.next()== true){
                txtidbuku.setText(rs.getString(2));
                txtJudulBuku.setText(rs.getString(3));
                txtJenisBuku.setText(rs.getString(4));
                txtnamaPenulis.setText(rs.getString(5));
                txtnamaPenerbit.setText(rs.getString(6));
                txttahunTerbit.setText(rs.getString(7));

            }
        } catch (SQLException ex) {
            Logger.getLogger(CRUD_Pbo1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_viewActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        txtidbuku.setText("");
        txtJudulBuku.setText("");
        txtJenisBuku.setText("");
        txtnamaPenulis.setText("");
        txtnamaPenerbit.setText("");
        txttahunTerbit.setText("");
        txtid.requestFocus();
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_ADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ADDActionPerformed
        try {
            String idbuku      = txtidbuku.getText();
            String judul    = txtJudulBuku.getText();
            String jenis    = txtJenisBuku.getText();
            String penulis  = txtnamaPenulis.getText();
            String penerbit  = txtnamaPenerbit.getText();
            String tahun  = txttahunTerbit.getText();

            pst = con.prepareStatement("insert into data (id_buku,judul_buku,jenis_buku,nama_penulis,nama_penerbit,tahun_terbit)values (?,?,?,?,?,?)");
            pst.setString(1,idbuku);
            pst.setString(2,judul);
            pst.setString(3,jenis);
            pst.setString(4,penulis);
            pst.setString(5,penerbit);
            pst.setString(6,tahun);

            int k = pst.executeUpdate();

            if (k==1){
                JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan");
                txtidbuku.setText("");
                txtJudulBuku.setText("");
                txtJenisBuku.setText("");
                txtnamaPenulis.setText("");
                txtnamaPenerbit.setText("");
                txttahunTerbit.setText("");
                txtid.requestFocus();
                loadPusakaId();
            }
            else{
                JOptionPane.showMessageDialog(this,"Data Tidak Berhasil Ditambahkan");
            }

        } catch (SQLException ex) {
            Logger.getLogger(CRUD_Pbo1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_ADDActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pbo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pbo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pbo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Pbo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Pbo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_ADD;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_view;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtJenisBuku;
    private javax.swing.JTextField txtJudulBuku;
    private javax.swing.JComboBox<String> txtid;
    private javax.swing.JTextField txtidbuku;
    private javax.swing.JTextField txtnamaPenerbit;
    private javax.swing.JTextField txtnamaPenulis;
    private javax.swing.JTextField txttahunTerbit;
    // End of variables declaration//GEN-END:variables
}
